// The Halloween maps from TF2's casual menu, shared by the UI, the server and the scripts.
// halloween-maps.json is generated by scripts/extract-game.ts.

import mapsJson from './halloween-maps.json' with { type: 'json' };

export type HalloweenMap = {
  /** BSP name (e.g. koth_harvest_event). Stable key for progress. */
  code: string;
  /** In-game display name. */
  name: string;
  /** Casual menu tab, e.g. "Special Events". */
  tab: string;
  /** Group inside the tab, e.g. "Halloween (Featured)". */
  section: string;
  /** Game mode, as the game names it. */
  mode: string;
  /** master_maps_list index; the map's bit in casual_criteria.vdf's selected_maps_bits. */
  mapIndex: number;
  /** ConTracker node defindex for this map's Halloween contract. */
  contractNode: number;
  /** ConTracker folder holding the contract, as the game labels it (e.g. "community_maps_2"). */
  contractFolder: string;
  /** Public path of the map screenshot. */
  image: string;
  wikiUrl: string;
};

export const MAPS: HalloweenMap[] = mapsJson;
export const MAP_BY_CODE = new Map(MAPS.map((map) => [map.code, map]));
